Feature/ctools 295
finbourne/lusid-sdk-generator-java pull request #12
Opened 2024-08-13 12:09 UTC by cg-finbourne

# Pull Request Checklist

- [ ] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [ ] Tests pass
- [ ] Raised the PR against the `develop` branch

# Description of the PR

Describe the code changes for the reviewers, explain the solution you have provided and how it fixes the issue

2024-08-13 12:13 UTC, cg-finbourne commented on generate/templates/other/ApiFactoryBuilder.mustache
> -    private static final int DEFAULT_TIMEOUT_SECONDS = 10;
this was not actually used by anything. The default timeout of the http client is also 10s so perhaps it was added for documentation

2024-08-13 12:14 UTC, cg-finbourne commented on generate/templates/other/FileConfigurationLoader.mustache
> +    public ClassLoader getClassLoader(){
made public because the tests are now in another namespace and need to use them

2024-08-13 12:17 UTC, cg-finbourne commented on generate/templates/pom.dev.mustache
> +            <artifactId>junit-vintage-engine</artifactId>
junit vintage allows junit 4 and junit 5 to be run in the same project. I could only get the environment variables setup required for the new unit tests with the junit 5 version of system stubs (https://github.com/webcompere/system-stubs/blob/main/system-stubs-jupiter/README.md)

2024-08-13 12:23 UTC, cg-finbourne commented on justfile
> +    mv {{justfile_directory()}}/generate/.output/sdk/src/test/java/com/finbourne/TO_BE_REPLACED {{justfile_directory()}}/generate/.output/sdk/src/test/java/com/finbourne/${PROJECT_NAME}
the changes here are because I moved where the test files go in the project. This is because I wanted to separate the unit and integration tests so that it was possible to run each separately. This is because the unit tests now require that no 'FBN' environment variables are set, so that the behaviour when they don't exist can be tested, but some env vars are required for auth in the integration tests

2024-08-13 12:26 UTC, cg-finbourne commented on justfile
> +        find {{justfile_directory()}}/generate/.output/sdk/src/test -type f -exec sed -i -e "s/TO_BE_REPLACED_UPPER_SNAKECASE/${upper_case_placeholder}/g" {} \;
this isn't ideal - in a future mr we should add the tests to the templates so we don't have to do this bash. Will require adding files like we do here https://github.com/finbourne/lusid-sdk-generator-java/blob/main/generate/config-template.json#L26. We would have to decide whether we wanted to publish the tests with the sdk in github or remove them before committing

2024-08-13 12:31 UTC, cg-finbourne commented on justfile
> +        harbor.finbourne.com/tools/sdk-server-stub-base \
in order for the system stub library (added for the env vars in the unit tests) to work a newer version of openjdk is required - see https://gitlab.com/finbourne/infra-experimental/sdk-server-stubs/-/merge_requests/3/diffs. This image is now used for the test stage of the pipeline - change here as well for consistency

2024-08-13 13:19 UTC, AndrewNeudegg requested changes

2024-08-13 13:19 UTC, AndrewNeudegg commented on generate/templates/README.mustache
> +# the sdk client timeout in milliseconds - the default is 1800000 (30 minutes)
Please could you add a warning that explains that the longer the timeout the more likely that request failure becomes. In some cases there may be a more efficent and reliable way to make requests than waiting longer

2024-08-13 13:20 UTC, AndrewNeudegg commented on justfile
> +        harbor.finbourne.com/tools/sdk-server-stub-base \
does this have any implications for an sdk consumer?

2024-08-15 07:01 UTC, cg-finbourne commented on justfile
> +        harbor.finbourne.com/tools/sdk-server-stub-base \
the server stub library is only used in the tests, so doesn't require a newer jdk version unless we commit the tests with the sdk which we are not currently doing. If there are any compile errors related to the java version being used then these should be surfaced during the generation stage still, as this image is not being changed

2024-08-22 12:55 UTC, AndrewNeudegg commented on generate/templates/README.mustache
> +For some configuration it is also possible to override the global configuration at the ApiFactory level, or at the request level. For the set of configuration which can be overridden, please see [Con
`[ConfigurationOptions](sdk/src/main/java/com/finbourne/horizon/extensions/ConfigurationOptions.java)` do we want to link to the Horizon one specifically?

2024-08-22 13:05 UTC, AndrewNeudegg commented on generate/templates/ApiClient.mustache
> +        if (opts.noOptionsSet()) {
We should null check opts

2024-08-22 14:55 UTC, AndrewNeudegg approved these changes

2024-08-22 15:11 UTC, merged